# Generated by Django 2.1.2 on 2019-03-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='pinglun',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='node',
            field=models.TextField(),
        ),
    ]
